const PlayersData = [
  {
    name: "MS Dhoni",
    position: "Wk Batsman",
    batting: "Right Handed",
    bowling: "Medium Seam",
    nationality: "Indian",
    salary: 150000,
    image: "https://documents.iplt20.com/ipl/IPLHeadshot2024/57.png",
  },
  {
    name: "Suresh Raina",
    position: "Batsman",
    batting: "Left Handed",
    bowling: "Off spin",
    nationality: "Indian",
    salary: 120000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/14.png",
  },
  {
    name: "Ravindra Jadeja",
    position: "All-rounder",
    batting: "Left Handed",
    bowling: "Leg spin",
    nationality: "Indian",
    salary: 110000,
    image: "https://documents.iplt20.com/ipl/IPLHeadshot2024/46.png",
  },
  {
    name: "Imran Tahir",
    position: "Bowler",
    batting: "Right Handed",
    bowling: "Wrist spin",
    nationality: "South African",
    salary: 80000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/898.png",
  },
  {
    name: "Faf du plessis",
    position: "Batsman",
    batting: "Right Handed",
    bowling: "Leg spin",
    nationality: "South African",
    salary: 50000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/24.png",
  },
  {
    name: "Sam Curran",
    position: "All-rounder",
    batting: "Left Handed",
    bowling: "Medium Seam",
    nationality: "English",
    salary: 70000,
    image: "https://i.ibb.co.com/KxHyHNdn/HD-wallpaper-sam-curran-chutty-kuzhathai-csk-sam-curran-whistle-podu-yellow-thumbnail-removebg-previ.png",
  },
  {
    name: "Dwane Bravo",
    position: "All-rounder",
    batting: "Right Handed",
    bowling: "Medium Seam",
    nationality: "West Indian",
    salary: 100000,
    image: "https://assets.iplt20.com/ipl/IPLHeadshot2022/25.png",
  },
  {
    name: "Deepak Chahar",
    position: "Bowler",
    batting: "Right Handed",
    bowling: "Medium Seam",
    nationality: "Indian",
    salary: 85000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/140.png",
  },
  {
    name: "Mitchell Santner",
    position: "All-rounder",
    batting: "Left Handed",
    bowling: "Orthodox",
    nationality: "New Zealander",
    salary: 65000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/1903.png",
  },
  {
    name: "Ruturaj Gaikwad",
    position: "Batsman",
    batting: "Right Handed",
    bowling: "Off spin",
    nationality: "Indian",
    salary: 44000,
    image: "https://documents.iplt20.com/ipl/IPLHeadshot2025/102.png",
  },
  {
    name: "Josh Hazlewood",
    position: "Bowler",
    batting: "Right Handed",
    bowling: "Fast Seam",
    nationality: "Australian",
    salary: 37000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/857.png",
  },
  {
    name: "Shardul Thakur",
    position: "Bowler",
    batting: "Right Handed",
    bowling: "Medium Seam",
    nationality: "Indian",
    salary: 40000,
    image: "https://documents.iplt20.com/ipl/IPLHeadshot2024/105.png",
  },
  {
    name: "Ambati Rayadu",
    position: "Batsman",
    batting: "Right Handed",
    bowling: "Off spin",
    nationality: "Indian",
    salary: 55000,
    image: "https://documents.iplt20.com/ipl/IPLHeadshot2023/60.png",
  },
  {
    name: "Narayan Jagadeesan",
    position: "Wk Batsman",
    batting: "Right Handed",
    bowling: "N/A",
    nationality: "Indian",
    salary: 20000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/4942.png",
  },
  {
    name: "Lungi Ngidi",
    position: "Bowler",
    batting: "Right Handed",
    bowling: "Fast spin",
    nationality: "South African",
    salary: 25000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/3746.png",
  },
  {
    name: "Karn Sharma",
    position: "All-rounder",
    batting: "Right Handed",
    bowling: "Leg Spin",
    nationality: "Indian",
    salary: 23500,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/1118.png",
  },
  {
    name: "KM Asif",
    position: "All-rounder",
    batting: "Right Handed",
    bowling: "Medium Seam",
    nationality: "Indian",
    salary: 25000,
    image: "https://documents.iplt20.com/playerheadshot/ipl/210/4944.png",
  },
];

export default PlayersData;
